---
title: "iOLab"
---

## Overview

The [iOLab](http://iolab.science) is a handheld wireless lab device created by **Mats Selen and Tim Stelzer at UIUC**. Penn State has used it since 2015 in the physics-for-majors course sequence. It is available for purchase or rental from [MacMillan](https://www.macmillanlearning.com/college/us/digital/iolab).

::: {.callout-tip}
## Download Lab Materials

- [Mechanics Labs (zip)](https://sites.psu.edu/lleblond/files/2020/06/MechanicsIOLABPennState.zip)
- [E&M Labs (zip)](https://sites.psu.edu/lleblond/files/2020/06/EMLabsIOLabPennState.zip)
- [Paper describing objectives and structure (arXiv)](https://arxiv.org/abs/2006.15181)
:::

## Online Instruction

Starting summer 2018, Phys 211 and Phys 212 have been offered completely online with 20--50 students per semester. The majority are adult learners working on software engineering degrees through Penn State World Campus.

The iOLab creates a lab experience similar to residential instruction using PASCO equipment. Students perform labs at home individually, submit lab reports, and have multiple communication channels for group work and instructor feedback.

Lab objectives focus on **data sense-making and observational experimental skills**, influenced by the [ISLE framework](http://www.islephysics.net/). Students use visual tools such as box plots and scatterplots, along with the web-based application [StatKey](http://www.lock5stat.com/StatKey/) for data visualization.

Courses include 5--6 proctored exams including pre/post FCI and BEMA.

## Phys 211: Mechanics (calc-based)

**Equipment:** iOLab (includes spring)\
**Software:** iOLab software, Excel, Word, StatKey

| Lab | Title | Materials |
|-----|-------|-----------|
| 1 | Getting Moving (introductory, step-by-step) | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-1.docx) |
| 2 | Slowing Down (first open-ended lab, ISLE rubric) | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-2.docx) |
| 3 | A Model for Kinetic Friction, Part 1 | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-3.docx) |
| 4 | A Model for Kinetic Friction, Part 2 | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-4.docx) |
| 5 | Hooke's Law, Part A | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-5.docx) |
| 6 | Hooke's Law, Part B | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-6.docx) |
| 7 | Rotation | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-7.docx) |
| 8 | Other Mechanical Sensors | [docx](https://sites.psu.edu/lleblond/files/2019/08/Lab-8.docx) |

## Phys 212: Electricity & Magnetism (calc-based)

**Equipment:** iOLab + [PASCO Desktop Electricity Kit](https://www.pasco.com/prodCatalog/EM/EM-8675_desktop-electricity-kit/index.cfm)\
**Software:** iOLab software, Excel, Word, StatKey + [PhET simulations](https://phet.colorado.edu)

| Lab | Title | Materials |
|-----|-------|-----------|
| 1 | Static Electricity | [docx](https://sites.psu.edu/lleblond/files/2019/10/Lab1.docx) |
| 2a | Electric Field (virtual, PhET) | [docx](https://sites.psu.edu/lleblond/files/2019/10/Lab2part1.docx) |
| 2b | Electric Field (virtual, PhET) | [docx](https://sites.psu.edu/lleblond/files/2019/10/Lab2part2.docx) |
| 3 | How a Capacitor Works | [docx](https://sites.psu.edu/lleblond/files/2019/10/Lab3.docx) |
| 4 | Resistance and Ohm's Law | [docx](https://sites.psu.edu/lleblond/files/2019/10/Lab4.docx) |
| 5 | Understanding RC Circuits | [docx](https://sites.psu.edu/lleblond/files/2019/10/lab5.docx) |
| 6 | Magnetic Fields | [docx](https://sites.psu.edu/lleblond/files/2019/10/LAB6.docx) |
| 7 | Faraday's Law | [docx](https://sites.psu.edu/lleblond/files/2019/10/Lab7.docx) |
| 8 | RLC Circuits (virtual, PhET) | [docx](https://sites.psu.edu/lleblond/files/2019/10/Lab8.docx) |
